// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asirko/go-template/internal/adapter/handler/http"
	"github.com/asirko/go-template/internal/adapter/repository/postgres"
	"github.com/asirko/go-template/internal/core/port"
	"github.com/asirko/go-template/internal/core/service"
)

import (
	_ "github.com/asirko/go-template/docs"
)

// Injectors from wire.go:

func InitializeEvent(token port.TokenService, db *repository.DB) (*handler.Router, error) {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	authService := service.NewAuthService(userRepository, token)
	authHandler := handler.NewAuthHandler(authService)
	router, err := handler.NewRouter(token, userHandler, authHandler)
	if err != nil {
		return nil, err
	}
	return router, nil
}
